[package]
name = "panbuild"
version = "0.0.4"
authors = ["louib <code@louib.net>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
clap = "2.33.1"
linked-hash-map = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
