# See https://doc.rust-lang.org/cargo/reference/config.html
# for all the options.

[build]
jobs = 4                  # number of parallel jobs, defaults to # of CPUs
rustc = "rustc"           # the rust compiler tool
rustdoc = "rustdoc"       # the doc generator tool
target-dir = "target"     # path of where to place all generated artifacts
rustflags = ["-Adead_code", "-Aunused"]
incremental = true        # whether or not to enable incremental compilation
pipelining = false        # rustc pipelining


[profile.dev]            # Modify profile settings via config.
opt-level = 0            # Optimization level.
debug = false            # Include debug info.
debug-assertions = true  # Enables debug assertions.
overflow-checks = true   # Enables runtime integer overflow checks.
lto = false              # Sets link-time optimization.
panic = 'unwind'         # The panic strategy.
incremental = true       # Incremental compilation.
codegen-units = 16       # Number of code generation units.
rpath = false            # Sets the rpath linking option.
