name: flatpak-build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: adding PPA for latest flatpak version.
      run: add-apt-repository ppa:alexlarsson/flatpak
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: installing flatpak and flatpak-builder
      run: sudo apt-get install -y flatpak flatpak-builder
    - name: printing flatpak version
      run: flatpak --version
    - name: printing flatpak-builder version
      run: flatpak-builder --version
    - name: adding flathub repo
      run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: installing the flatpak runtime and SDK
      run: flatpak install -y --user flathub org.gnome.Platform/x86_64/3.36 org.gnome.Sdk/x86_64/3.36
    - name: installing the rust extension
      run: flatpak install -y --user flathub org.freedesktop.Sdk.Extension.rust-stable//19.08
    - name: converting manifest to JSON
      run: python3 scripts/yml2json net.louib.panbuild.yml > net.louib.panbuild.json
    - name: building the flatpak
      run: flatpak-builder --user --force-clean build net.louib.panbuild.json
