name: linterzzz

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: installing shellcheck
      run: sudo apt-get install -y shellcheck
    - name: printing rust version
      run: rustc --version
    - name: printing cargo version
      run: cargo --version
    - name: running shellcheck on shell scripts
      run: shellcheck scripts/*.sh
    - name: running shellcheck on shell scripts
      run: shellcheck tests/*.sh
    - name: running rustfmt
      run: rustfmt src/*.rs
