name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: printing rust version
      run: rustc --version
    - name: printing cargo version
      run: cargo --version
    - name: building the project
      run: cargo build
    - name: running the unit tests
      run: cargo test
    - name: installing the app
      run: PANBUILD_INSTALL_DIR=/usr/share/bin/ ./scripts/install.sh
    - name: running the binary smoke tests
      run: bash tests/smoke_tests.sh
